Metrics/LineLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 10

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Lint/Eval:
  Enabled: false
